program: train.py
method: bayes

metric:
  name: Test/accuracy
  goal: maximize

parameters:
  train.lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  
  train.batch_size:
    values: [16, 32, 64, 128]
  

  model.params.hidden_dim:
    values: [64, 128, 256]
  
  model.params.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  
  model.params.cnn_dropout:
    distribution: uniform
    min: 0.0
    max: 0.3
  
  loss.params.gamma:
    distribution: uniform
    min: 0.0
    max: 2.0

early_terminate:
  type: hyperband
  min_iter: 3

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}