hydra:
  run:
    dir: .

# Data sources
data:
  data_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/SeparatedAudio"
  label_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Label"

# Dataset configuration
dataset:
  name: "MelFrameDataset"
  params:
    num_classes: 4
    sr: 16000
    channels: 'mono'
    window: 20
    n_fft: 2048
    hop_length: 512
    target_bins: 80
    aug: True

# Model
model:
  name: "Conv2DGRU"
  params:
    num_layers: 3
    in_channels: 1
    num_bins: ${dataset.params.target_bins}

    last_hidden_dim: 128
    use_gradual_size: False

    kernel_size: 3
    pool_size: (2,1)
    dilation: (1,2)
    cnn_dropout: 0

    num_gru: 3
    hidden_dim: 128
    dropout: 0.3
    num_classes: 4

# Loss params
loss:
  name: FocalLoss # If alpha=1 gamma=0: FocalLoss -> CrossEntropyLoss
  params:
    alpha: 1
    gamma: 0.0
    ignore_index: 3

# Training parameters
train:
  trainer: "FrameTrainer"
  lr: 5e-4
  batch_size: 32
  num_iterations: 5000
  eval_interval: 200
  save_interval: 1000
  random_seed: 42
  selection: Stratify

# Cross-validation parameters
kfold:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}

stratify: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Stratify/stratify_back.csv"


# Directory paths
dir:
  save_dir: "weights/frame"