hydra:
  run:
    dir: .

defaults:
  - models: ChromaCNN
  - datasets: ChromaDataset

data:
  audio_dir: "/Users/jcastle/workspace/pansori/Pansori_2025_ISMIR/data/Audio"
  label_json: "/Users/jcastle/workspace/pansori/Pansori_2025_ISMIR/data/label.json"

train:
  lr: 1e-4
  batch_size: 16
  num_empochs: 50
  random_seed: 42

kfold:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}

dir:
  save_dir: "/Users/jcastle/workspace/pansori/Pansori_2025_ISMIR/train/weights"
  best_dir: "/Users/jcastle/workspace/pansori/Pansori_2025_ISMIR/train/best_model"