hydra:
  run:
    dir: .

defaults:
  - models: ChromaCNNLSTM
  - datasets: ChromaDataset

data:
  audio_dir: "/home/sangheon/Desktop/Pansori/Audio"
  label_json: "/home/sangheon/Desktop/Pansori_2025_ISMIR/data/label.json"

train:
  lr: 5e-3
  batch_size: 8
  num_epochs: 50
  random_seed: 42

kfold:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}

loocv:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}
dir:
  save_dir: "/home/sangheon/Desktop/Pansori_2025_ISMIR/train/weights"
  best_dir: "/home/sangheon/Desktop/Pansori_2025_ISMIR/train/best_model"
