hydra:
  run:
    dir: .

# Data sources
data:
  data_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/CrepePitch"
  label_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Label"

# Dataset configuration
dataset:
  name: "PitchSegmentDataset"
  params:
    num_classes: 3
    frame_rate: 20
    window: 20
    threshold: 0.0
    aug: True

model:
  name: "SegConv1DGRU"
  params:
    num_layers: 3
    in_channels: 2

    last_hidden_dim: 128
    use_gradual_size: True

    kernel_size: 3
    pool_size: 2 # False
    dilation: 1
    cnn_dropout: 0.5

    num_gru: 3
    hidden_dim: 128
    dropout: 0.3

    num_frames : ${dataset.params.window}*${dataset.params.frame_rate}
    num_classes: ${dataset.params.num_classes}

# Loss params
# If alpha=1 gamma=0: FocalLoss -> CrossEntropyLoss
loss:
  name: FocalLoss
  params:
    alpha: 1
    gamma: 0
    ignore_index: -100

# Training parameters
train:
  trainer: "SegmentTrainer"
  lr: 5e-4
  batch_size: 32
  num_iterations: 5000
  eval_interval: 200
  save_interval: 1000
  random_seed: 42
  selection: Stratify # KFold

# Cross-validation parameters
kfold:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}

stratify: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Stratify/stratify_back_without_oche.csv"

# Directory paths
dir:
  save_dir: "weights/segment"