program: sweep_train.py
method: grid

metric:
  name: Test/Avg Acc
  goal: maximize

parameters:
  model.params.dropout:
    values: [0.0, 0.3]

  model.params.cnn_dropout:
    values: [0.0, 0.5]

  model.params.num_gru:
    values: [3, 5]

  model.params.num_layers:
    values: [3, 5]

  model.params.use_gradual_size:
    values: [True, False]

  loss.params.gamma:
    values: [0.0, 1.0]

command:
  - /home/jinin/userdata/Pansori_2025_ISMIR/pansori_venv/bin/python
  - sweep_train.py
  - --config-path=configs/segment
  - --config-name=mel_base
  - hydra.run.dir=.