hydra:
  run:
    dir: .

# Data sources
data:
  data_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/PestoPitch"
  label_dir: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Label"

# Dataset configuration
dataset:
  name: "PitchDataset"
  params:
    num_classes: 4
    frame_rate: 20
    window: 20
    threshold: 0.1
    aug: True

model:
  name: "Conv1DGRU"
  params:
    num_layers: 3
    in_channels: 2
    last_hidden_dim: 128
    use_gradual_size: True

    kernel_size: 3
    pool_size: False
    dilation: 1

    num_gru: 3
    hidden_dim: 128
    dropout: 0.3
    num_classes: 4

# Loss params
# If alpha=1 gamma=0: FocalLoss -> CrossEntropyLoss
loss:
  name: FocalLoss
  params:
    alpha: 1
    gamma: 0
    ignore_index: 0

# Training parameters
train:
  lr: 5e-4
  batch_size: 32
  num_iterations: 4000
  eval_interval: 200
  save_interval: 1000
  random_seed: 42
  selection: Stratify

# Cross-validation parameters
kfold:
  n_splits: 5
  shuffle: True
  random_state: ${train.random_seed}

stratify: "/home/jinin/userdata/Pansori_2025_ISMIR/data/Stratify/stratify_back_without_oche.csv"


# Directory paths
dir:
  save_dir: "train/stratify"