# CNN Encoder
in_channels: 1
num_layers: 4
last_hidden_dim: 64
use_gradual_size: true
kernel_size: [3, 5]
dilation: [1, 1]
pool_size: [2, 1]
cnn_dropout: 0.1
num_bins : 128

# GRU
hidden_dim: 256
num_gru: 2
dropout: 0.4

# Classifier
num_classes: 5

